<div class="row sitemap">
    <?php $count = 0; ?>
    <?php $startNewRow = true; $colItemCount = 0; ?>
    <?php $pages = $this->container->getPages(); foreach ($pages as $key=>$page): ?>

        <?php $colItemCount++; ?>

        <?php if($startNewRow==true): ?>
        <?php $startNewRow = false; ?>
            <div class="col-xs-6">
        <?php endif; ?>

        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $colItemCount++; ?>
        <?php $hasChildren = $page->hasPages(); ?>
        <?php if(in_array($page->getLabel(),$this->config()['navigation']['options']['footer']['exclude_children'])){ $hasChildren=false; } ?>
        <?php if(!$hasChildren):  ?>
                <a class="sitemap-header" href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            <br/>
            <br/>
        <?php else: ?>

                <a href="<?=$page->getHref()?>" class="sitemap-header">
                    <?php echo $page->getLabel() ?>
                </a>

                <ul class="sitemap-section">
                    <?php $childPages = $page->getPages(); foreach($childPages as $childKey=>$child): ?>
                        <?php $colItemCount++; ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <li>
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
        <?php endif; ?>
        <?php $count++ ?>

        <?php if($colItemCount>13): ?>
            <?php $colItemCount=0; ?>
            <?php $startNewRow=true; ?>
            </div>
        <?php endif; ?>

    <?php endforeach ?>
    
    </div>

</div>