<div class="row sitemap">
    <?php $count = 0; ?>
    <?php $startNewRow = true; $colItemCount = 0; ?>
    <?php foreach ($this->container as $key=>$page): ?>

        <?php $colItemCount++; ?>

        <?php if($startNewRow==true): ?>
        <?php $startNewRow = false; ?>
            <div class="col-md-4">
        <?php endif; ?>

        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if(!$hasChildren): ?>
                <a class="sitemap-header" href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            <br/>
            <br/>
        <?php else: ?>

                <a href="<?=$page->getHref()?>" class="sitemap-header">
                    <?php echo $page->getLabel() ?>
                </a>

                <ul class="sitemap-section">
                    <?php foreach($page->getPages() as $child): ?>
                        <?php $colItemCount++; ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <li>
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $this->translate($child->getLabel()) ?>
                            </a>

                            <?php $hasMoreChildren = $child->hasPages() ?>

                            <?php if($hasMoreChildren): ?>
                                <ul>

                                    <?php foreach($child->getPages() as $anotherChild): ?>
                                        <?php $colItemCount++; ?>

                                        <li>
                                            <a href="<?php echo $anotherChild->getHref() ?>">
                                                &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->translate($anotherChild->getLabel()) ?>
                                            </a>
                                        </li>

                                        <?php $hasEvenMoreChildren = $child->hasPages() ?>

                                        <?php if($hasEvenMoreChildren): ?>

                                                <?php foreach($anotherChild->getPages() as $anotherChild2): ?>
                                                    <?php $colItemCount++; ?>

                                                    <li>
                                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo $anotherChild2->getHref() ?>">
                                                            <?php echo $this->translate($anotherChild2->getLabel()) ?>
                                                        </a>
                                                    </li>

                                                <?php endforeach; ?>


                                            <?php $count++ ?>
                                        <?php endif; ?>

                                    <?php endforeach; ?>

                                </ul>

                                <?php $count++ ?>
                            <?php endif; ?>

                        </li>
                    <?php endforeach ?>
                </ul>
        <?php endif; ?>
        <?php $count++ ?>

        <?php if($colItemCount>20 || count($this->container)==($key+1)): ?>
            <?php $colItemCount=0; ?>
            <?php $startNewRow=true; ?>
            </div>
        <?php endif; ?>

    <?php endforeach ?>
</div>
<!-- fix-me: rogue tag -->
</div>