<?php if($this->isXmlHttpRequest==true): ?>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <img src="/branding/vulcan/logos/vulcanHead130x130.png" style="width:80px;" class="pull-left" />
        &nbsp;&nbsp;
        <h2><?=$this->content->title?></h2>
    </div>
    <div class="modal-body">
        <?=$this->partial('layout/components/contact-form-min.phtml',array('noSubmit'=>true,'id'=>'contact-popup-form'))?>
    </div>
    <div class="modal-footer">

        <div class="pull-left">
            <h2><a class="emphasis" href="tel:<?=$this->config()['myapp']['contact']['phone_link']?>"><i class="fa fa-phone fa-1x" aria-hidden="true"></i> &nbsp; <?=$this->config()['myapp']['contact']['phone_formatted']?></a></h2>
        </div>

        <button type="button" class="btn btn-default" onclick="preventFurtherPopups();" data-dismiss="modal">Don't Show Again</button>
        <button type="button" class="btn btn-emphasis" onclick="submitContactPopup('#contact-popup-form');$('button[type=button], input[type=button]').prop('disabled',true);">Submit</button>
    </div>

<?php else: ?>

        <?=$this->cmsContent($this->content,$this)?>

<?php endif; ?>