<?=$this->partial('layout/components/gallery-db.phtml',array('gallery'=>$this->gallery))?>
<div class="container" id="home">

    <?=$this->cmsContent($this->content,$this)?>

    <hr/>

    <h1>News For Now <a class="fa fa-angle-double-right" href="/blog"></a></h1>
    <p>What is happening now at <?=$this->config()['myapp']['contact']['company_name']?>.</p>
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-lg-4">
            <?=$this->partial('layout/components/post.phtml',array('post'=>$this->blog[0]))?>
        </div>
        <div class="col-lg-4">
            <?=$this->partial('layout/components/post.phtml',array('post'=>$this->blog[1]))?>
        </div>
        <div class="col-lg-4">
            <?=$this->partial('layout/components/post.phtml',array('post'=>$this->blog[2]))?>
        </div>
    </div>

</div>