<div class="blog-post-small">
    <h3><?=$this->post->title?></h3>
    <div class="text-muted"><?=$this->post->posted_timestamp->format('M j Y')?> by Vulcan<sup>&reg;</sup> Systems</div>
    <br/>
    <img src="<?=$this->post->getImageThumb()?>" alt="<?=$this->post->description?>" title="<?=$this->post->title?>" />
    <?=$this->post->contentShort?>
    <p><a class="btn btn-emphasis" href="/blog/<?=$this->post->key?>/all" role="button">Read More &raquo;</a></p>
</div>