<h2><a class="emphasis" href="tel:<?=$this->config()['myapp']['contact']['phone_link']?>"><i class="fa fa-phone fa-1x" aria-hidden="true"></i> &nbsp; <?=$this->config()['myapp']['contact']['phone_formatted']?></a></h2>
<h2><a class="emphasis" href="mailto:<?=$this->config()['myapp']['contact']['email']?>"><i class="fa fa-envelope fa-1x" aria-hidden="true"></i> &nbsp; <?=$this->config()['myapp']['contact']['email']?></a></h2>
<br/><br/>
<h3>
    <?=$this->config()['myapp']['contact']['company_name']?><br/>
    <?=$this->config()['myapp']['contact']['street']?><br/>
    <?=$this->config()['myapp']['contact']['city']?>, <?=$this->config()['myapp']['contact']['state']?> <?=$this->config()['myapp']['contact']['zip']?>
</h3>
<br/>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3081.40740074462!2d-92.45576904842791!3d39.4375229793903!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87dd2d36579d5745%3A0xc00406fca2d009c!2sVulcan%C2%AE+Systems!5e0!3m2!1sen!2sus!4v1461622124734" width="80%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>