<?=$this->partial('layout/components/banner.phtml',array('text'=>$this->content->title.' - '.ucwords($this->category),'src'=>'whoweare.jpg'))?>
<div class="container">

    <?=$this->cmsContent($this->content,$this)?>

    <div class="row">
        <div class="col-md-10">

            <?php if($this->category!=='all'): ?>
                <a href="<?=$this->url('blog')?>"><i class="fa fa-chevron-left fa-lg"></i> All Articles</a>
            <?php endif; ?>

            <?php foreach($this->blog as $post): ?>
                <div class="row">
                    <div class="col-md-9">
                        <h2><?=$post->title?></h2>
                        <div class="text-muted"><?=$post->posted_timestamp->format('M j Y')?> by Vulcan<sup>&reg;</sup> Systems</div>
                        <br/>
                        <?=$post->contentShort?>
                        <?php if($category!=='call'): ?>
                            <a class="btn btn-emphasis" href="<?=$this->url('blog-post',array('key'=>$post->key,'category'=>$this->category))?>">Read More</a>
                        <?php else: ?>
                            <a class="btn btn-emphasis" href="<?=$this->url('blog-post',array('key'=>$post->key))?>">Read More</a>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-3">
                        <img src="<?=$post->getImageThumb()?>" alt="<?=$post->title?>" class="image-responsive" style="width:100%;" />
                    </div>
                </div>
                <hr/>
            <?php endforeach; ?>

        </div>
        <div class="col-md-2">

            <h1>Categories</h1>
            <ul>
                <li><a href="<?=$this->url('blog')?>">All</a></li>
            <?php foreach($this->categories as $category): ?>
                <li><a href="<?=$this->url('blog',array('category'=>$category['category']))?>" rel="nofollow"><?=$category['category']?></a> (<?=$category[1]?>)</li>
            <?php endforeach; ?>
            </ul>

        </div>
    </div>

</div>
