<?=$this->cmsContent($this->content,$this)?>
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <?=$this->partial('delamatre-zend-cms/blog/components/list.phtml',array('category'=>$this->category,'blog'=>$this->blog));?>
        </div>
        <div class="col-md-2">
            <h2>Categories</h2>
            <?=$this->partial('delamatre-zend-cms/blog/components/category-list.phtml',array('categories'=>$this->categories));?>
        </div>
    </div>
</div>